INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `metadata`, `desc`, `weight`) VALUES 
  ('joint', 'Marijuana joint', 10, 1, 'item_standard', 1, '{}', 'A marijuana joint.', 0.1),
  ('cigpack1', 'Cigarette pack (1 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 1 cigarette remaining.', 0.1),
  ('cigpack2', 'Cigarette pack (2 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 2 cigarettes remaining.', 0.1),
  ('cigpack3', 'Cigarette pack (3 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 3 cigarettes remaining.', 0.1),
  ('cigpack4', 'Cigarette pack (4 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 4 cigarettes remaining.', 0.1),
  ('cigpack5', 'Cigarette pack (5 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 5 cigarettes remaining.', 0.1),
  ('cigpack6', 'Cigarette pack (6 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 6 cigarettes remaining.', 0.1),
  ('cigpack7', 'Cigarette pack (7 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 7 cigarettes remaining.', 0.1),
  ('cigpack8', 'Cigarette pack (8 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 8 cigarettes remaining.', 0.1),
  ('cigpack9', 'Cigarette pack (9 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 9 cigarettes remaining.', 0.1),
  ('cigpack10', 'Cigarette pack (10 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigarette pack with 10 cigarettes remaining.', 0.1),
  ('cigarpack1', 'Cigar pack (1 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigar pack with 1 cigar remaining.', 0.1),
  ('cigarpack2', 'Cigar pack (2 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigar pack with 2 cigars remaining.', 0.1),
  ('cigarpack3', 'Cigar pack (3 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigar pack with 3 cigars remaining.', 0.1),
  ('cigarpack4', 'Cigar pack (4 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigar pack with 4 cigars remaining.', 0.1),
  ('cigarpack5', 'Cigar pack (5 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigar pack with 5 cigars remaining.', 0.1),
  ('cigarpack6', 'Cigar pack (6 remaining)', 10, 1, 'item_standard', 1, '{}', 'A cigar pack with 6 cigars remaining.', 0.1),
  ('jointpack1', 'Joint pack (1 remaining)', 10, 1, 'item_standard', 1, '{}', 'A joint pack with 1 joint remaining.', 0.1),
  ('jointpack2', 'Joint pack (2 remaining)', 10, 1, 'item_standard', 1, '{}', 'A joint pack with 2 joints remaining.', 0.1),
  ('jointpack3', 'Joint pack (3 remaining)', 10, 1, 'item_standard', 1, '{}', 'A joint pack with 3 joints remaining.', 0.1),
  ('jointpack4', 'Joint pack (4 remaining)', 10, 1, 'item_standard', 1, '{}', 'A joint pack with 4 joints remaining.', 0.1),
  ('jointpack5', 'Joint pack (5 remaining)', 10, 1, 'item_standard', 1, '{}', 'A joint pack with 5 joints remaining.', 0.1),
  ('chewingtobacco', 'Chewing tobacco', 100, 1, 'item_standard', 1, '{}', 'Your box is full', 0.1),
  ('chewingtobacco2', 'Chewing tobacco', 100, 1, 'item_standard', 1, '{}', 'You have 4 doses left', 0.1),
  ('chewingtobacco3', 'Chewing tobacco', 100, 1, 'item_standard', 1, '{}', 'You have 3 doses left', 0.1),
  ('chewingtobacco4', 'Chewing tobacco', 100, 1, 'item_standard', 1, '{}', 'You have 2 doses left', 0.1),
  ('chewingtobacco5', 'Chewing tobacco', 100, 1, 'item_standard', 1, '{}', 'You have 1 dose left', 0.1),
  ('cigarette', 'Cigarette', 200, 1, 'item_standard', 1, '{}', 'A loose cigarette', 0.1),
  ('cigar', 'Ciga', 200, 1, 'item_standard', 1, '{}', 'A loose cigar', 0.1),
  ('picadura', 'Tobacco cut', 200, 1, 'item_standard', 1, '{}', 'Pipe tobacco cut', 0.1),
  ('opium', 'Opium', 10, 1, 'item_standard', 1, '{}', 'A bit of opium to smoke', 0.1),
  ('opium_pipe', 'Opium pipe', 10, 1, 'item_standard', 1, '{}', 'A pipe for smoking opium', 0.1),
  ('pipe', 'Pipe', 10, 1, 'item_standard', 1, '{}', 'A pipe for smoking', 0.1),
  ('mushroom', 'Hallucinogenic mushrooms', 10, 1, 'item_standard', 1, '{}', 'Mushrooms to have a good time', 0.1),
  ('lighter', 'Lighter', 200, 1, 'item_standard', 1, '{}', 'A lighter for smokers', 0.1);

 
